stages:
  - build
  - test
  - publish
  - cleanup

variables:
  LDAP_IMAGE_VERSION: "1.0.1"

# ------------------------------------------
# Build

build_image:
  stage: build
  tags:
    - dockerbuild
  variables:
    BUILD_OPTS: "--force-rm --no-cache"
  script:
    - echo "Building article714/openldap-container:${LDAP_IMAGE_VERSION}"
    - docker build ${BUILD_OPTS} -t article714/openldap-container:${LDAP_IMAGE_VERSION} .

# ------------------------------------------
# Tests

test_image:
  stage: test
  image:
    name: article714/openldap-container:${LDAP_IMAGE_VERSION}
  services:
    - name: article714/openldap-container:${LDAP_IMAGE_VERSION}
      alias: ldap-srv
      command: ["initpwd", "bonjour"]
  tags:
    - docker
  script:
    # wait for Ldap to be fully fit
    - sleep 10
    - python3 -m tests.runtests
