language: python
sudo: false
cache: pip

services:
  - docker

script:
  - export BUILD_OPTS='--force-rm --no-cache'
  - export LDAP_CONTAINER_VERSION='1.0.1'
  - docker build ${BUILD_OPTS} -t article714/openldap-container:${LDAP_CONTAINER_VERSION} --build-arg LDAP_CONTAINER_VERSION=${LDAP_CONTAINER_VERSION} .
